apiVersion: v1
kind: Service
metadata:
  name: secure-config-test-node-port
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    component: secure-config-test