apiVersion: v1
kind: Service
metadata:
  name: secure-config-test-prod-node-port
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30033
  selector:
    component: secure-config-test-prod